version: "3.9"

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongodb:/data/db
  
  node-app:
    build: .
    command: npm run start
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URL=${MONGO_URI}
    depends_on:
      - mongodb

volumes:
  mongodb:
